v2.0 RELEASE

diff --git a/infamick b/infamick
--- a/infamick
+++ b/infamick
@@ -11,7 +11,24 @@ brand=$(getprop ro.product.system.brand)
 model=$(getprop ro.product.system.model)
 INDENT="    "
 INDENTN="\n    "
+CHARGING_PATH="/sys/class/power_supply/battery/charging_enabled"
 
+reboot_quest() {
+    read -n 1 confirm_choice
+    case $confirm_choice in
+        [Yy]*)
+            printf "${INDENTN}${YELLOW}[i] Rebooting.. ${RESET}"
+            sleep 2
+            reboot
+            ;;
+        [nN])
+          printf "${INDENTN}${GREEN}[i] No reboot${RESET}\n"
+            ;;
+        *)
+            printf "${INDENTN}${RED}Error: Wrong option '$confirm_choice'${RESET}\n"
+            ;;
+    esac
+  }
 smg_check() {
             if echo "$brand" | grep -iq "samsung"; then
             export IS_SAMSUNG=1
@@ -393,26 +410,31 @@ services=(
 help_menu() {
     echo
     printf "\n${BOLD}infamick - System Utility Script${RESET}"
-    printf "\n${RED}${BOLD}v1.6 (202407291)"
+    printf "\n${RED}${BOLD}2.0 (202408069)"
     echo
     printf "\n${GREEN}Usage:${RESET} infamick ${BOLD}<command> ${BLUE}${BOLD}<2ndcommand>${RESET}"
     echo
     printf "\n${YELLOW}Available commands:${RESET}"
-    printf "\n  ${BOLD}batt_b${RESET}  - Improves battery draining"
-    printf "\n  ${BOLD}batt_i${RESET}  - Display battery health and charging cycles"
-    printf "\n            Shows the current battery health percentage"
-    printf "\n            and the number of charging cycles"
-    printf "\n  ${BOLD}batt_s${RESET}  - Open battery optimizations setting"
-    printf "\n            Run only while charging at 100"
+    printf "\n  ${BOLD}batt${RESET} ${BLUE}${BOLD}boost${RESET}   - Improves battery draining"
+        printf "\n                 Run only while charging at 100"
+    printf "\n  ${BOLD}batt${RESET} ${BLUE}${BOLD}info${RESET}    - Display battery health and"
+    printf "\n                 charging cycles"
+    printf "\n  ${BOLD}batt${RESET} ${BLUE}${BOLD}opt${RESET}     - Open battery optimizations setting"
+    printf "\n  ${BOLD}batt${RESET} ${BLUE}${BOLD}start${RESET}   - Enable battery charging"
+    printf "\n  ${BOLD}batt${RESET} ${BLUE}${BOLD}status${RESET}  - Show if charging is disabled/enabled"
+    printf "\n  ${BOLD}batt${RESET} ${BLUE}${BOLD}stop${RESET}    - Disable battery charging"
     echo
     printf "\n  ${BOLD}boot${RESET}    - Reset boot count settings"
     printf "\n            Sets global boot_count and"
     printf "\n            Phenotype_boot_count to 0"
     echo
+    printf "\n  ${BOLD}btmap${RESET}   - Show current Power, Volume Up and Volume"
+    printf "\n            Down buttons action and remap them"
+    echo
     printf "\n  ${BOLD}cache${RESET}   - Trim cache multiple times"
     echo
-    printf "\n  ${BOLD}dd${RESET}   - Backup all possible partitions"
-    printf "\n         chosing a name"
+    printf "\n  ${BOLD}dd${RESET}      - Backup all possible partitions"
+    printf "\n            chosing a name"
     echo
     printf "\n  ${BOLD}dsp_rs${RESET}  - Reset current display size and dpi"
     printf "\n  ${BOLD}dsp_set${RESET} - Change display size and dpi "
@@ -457,7 +479,7 @@ help_menu() {
     printf "\n            Press CTRL+C to exit temperature monitoring"
     echo
     printf "\n${GREEN}Examples:${RESET}"
-    printf "\n  infamick batt_i"
+    printf "\n  infamick batt stop"
     printf "\n  infamick gmsd"
     printf "\n  infamick exdim"
     printf "\n  infamick perf"
@@ -721,7 +743,7 @@ change_csc() {
     printf "${INDENT}${YELLOW}[i] Execution Succeed..! ${RESET}\n"
 }
 
-button_mapper() {
+bixby_mapper() {
     printf "${INDENTN}${YELLOW}[i] This function will remap the Bixby button${RESET}"
     printf "${INDENTN}${YELLOW}[i] in Generic.kl, Generic_internal.kl, or${RESET}"
     printf "${INDENTN}${YELLOW}gpio_keys.kl${RESET}"
@@ -836,11 +858,12 @@ button_mapper() {
 
     rm "$temp_file"
 
-    printf "${INDENTN}${GREEN}[+] Value for key 703 has been updated${RESET}"
+    printf "${INDENTN}${GREEN}[+] Value for Bixby Button has been updated${RESET}"
     printf "${INDENTN}${GREEN}to: ${BOLD_WHITE}%s${RESET}" "$new_value"
     printf "${INDENTN}${YELLOW}[i] Execution Succeed..! ${RESET}\n"
+    printf "${INDENTN}${BLUE}[!] Reboot to apply the changes? (Y/n): ${RESET}"
+    reboot_quest
 }
-
 
 battsettings() {
     printf "${INDENTN}${YELLOW}[i] This will redirect you to the Battery${RESET}"
@@ -943,20 +966,221 @@ dd_backup() {
     printf "${INDENT}${YELLOW}[i] Execution Successful..! ${RESET}\n"
 
 }
+button_mapper() {
+    printf "${INDENTN}${YELLOW}[i] This function will remap universal Android"
+    printf "${INDENTN}buttons${RESET}"
+    printf "${INDENTN}${YELLOW}[i] in Generic.kl, Generic_internal.kl, or${RESET}"
+    printf "${INDENTN}${YELLOW}gpio_keys.kl${RESET}"
+    printf "${INDENTN}${RED}[i] DO AT YOUR OWN RISK..!${RESET}"
+    printf "${INDENTN}${YELLOW}[i] Press ENTER when you are ready${RESET}"
+    read -r a
 
+    file1="/system/usr/keylayout/Generic.kl"
+    file2="/system/usr/keylayout/Generic_internal.kl"
+    file3="/system/usr/keylayout/gpio_keys.kl"
+    value=""
+    file=""
+
+    # Chiedi all'utente quale tasto vuole rimappare
+    printf "${INDENTN}${YELLOW}[?] Which button do you want to remap:${RESET}"
+    printf "${INDENTN}${BOLD_WHITE}1. Power"
+    printf "${INDENTN}${BOLD_WHITE}2. Volume Up"
+    printf "${INDENTN}${BOLD_WHITE}3. Volume Down"
+    printf "${INDENTN}${YELLOW}Enter your choice (1-3): ${RESET}"
+    read -r button_choice
+
+    case $button_choice in
+        1) key_code="116" 
+           buttonc="Power" ;;
+        2) key_code="115" 
+           buttonc="Volume Up" ;;
+        3) key_code="114" 
+           buttonc="Volume Down" ;;
+        *)
+            printf "${INDENTN}${RED}[!] Error: Invalid choice. Please enter${RESET}"
+            printf "${INDENTN}${RED}a number between 1 and 3.${RESET}\n"
+            return
+            ;;
+    esac
+
+    # Cerca nei file, dando priorità a Generic_internal.kl
+    if [ -f "$file2" ]; then
+        file="$file2"
+        value=$(grep "key $key_code" "$file2" | awk '{print $3}')
+    fi
+    
+    if [ -z "$value" ] && [ -f "$file1" ]; then
+        file="$file1"
+        value=$(grep "key $key_code" "$file1" | awk '{print $3}')
+    fi
+    
+    if [ -z "$value" ] && [ -f "$file3" ]; then
+        file="$file3"
+        value=$(grep "key $key_code" "$file3" | awk '{print $3}')
+    fi
+
+    if [ -n "$value" ]; then
+        printf "${INDENTN}${YELLOW}[*] Current value for $buttonc: ${BOLD_WHITE}%s${RESET}" "$value"
+    else
+        printf "${INDENTN}${RED}[!] Value not found for key $key_code${RESET}"
+        return
+    fi
+
+    printf "${INDENTN}${YELLOW}[?] Choose new value for the $buttonc button:${RESET}"
+    printf "${INDENTN}${BOLD_WHITE}1. APP_SWITCH - Recent apps button"
+    printf "${INDENTN}${WHITE_BOLD}2. BACK - back gesture "
+    printf "${INDENTN}${BOLD_WHITE}3. CALCULATOR - open calculator app"
+    printf "${INDENTN}${WHITE_BOLD}4. CALENDAR - open calendar app"
+    printf "${INDENTN}${BOLD_WHITE}5. CALL - open call app"
+    printf "${INDENTN}${BOLD_WHITE}6. CAMERA - starts camera app"
+    printf "${INDENTN}${BOLD_WHITE}7. CONTACTS - open contacts app"
+    printf "${INDENTN}${BOLD_WHITE}8. HOME - Homebutton"
+    printf "${INDENTN}${BOLD_WHITE}9. EXPLORER - Internet-browser"
+    printf "${INDENTN}${BOLD_WHITE}10. MENU - menu"
+    printf "${INDENTN}${BOLD_WHITE}11. MESSAGE - open message app"
+    printf "${INDENTN}${BOLD_WHITE}12. MEDIA_NEXT - next track"
+    printf "${INDENTN}${BOLD_WHITE}13. MEDIA_PLAY_PAUSE - play/pause"
+    printf "${INDENTN}${BOLD_WHITE}14. MEDIA_PREVIOUS - previous track "
+    printf "${INDENTN}${BOLD_WHITE}15. MUSIC - starts your favorite music player"
+    printf "${INDENTN}${BOLD_WHITE}16. PAGE_UP -  page up"
+    printf "${INDENTN}${BOLD_WHITE}17. PAGE_DOWN -  page down"
+    printf "${INDENTN}${BOLD_WHITE}18. POWER - Powermenu"
+    printf "${INDENTN}${BOLD_WHITE}19. QPANEL_ON_OFF - Notification panel"
+    printf "${INDENTN}${BOLD_WHITE}20. SEARCH - search"
+    printf "${INDENTN}${BOLD_WHITE}21. SLEEP -  sleep phone"
+    printf "${INDENTN}${BOLD_WHITE}22. SYSRQ - screenshot"
+    printf "${INDENTN}${BOLD_WHITE}23. VOICE_ASSIST - default voice assistant"
+    printf "${INDENTN}${WHITE_BOLD}24. VOLUME_DOWN - sets volume down"
+    printf "${INDENTN}${WHITE_BOLD}25. VOLUME_MUTE - volume on/off"
+    printf "${INDENTN}${BOLD_WHITE}26. VOLUME_UP - sets volume up"
+    printf "${INDENTN}${BOLD_WHITE}27. WAKEUP - wakeup phone"
+    printf "${INDENTN}${YELLOW}Enter your choice (1-27): ${RESET}"
+    read -r choice
+
+    case $choice in
+        1) new_value="APP_SWITCH" ;;
+        2) new_value="BACK" ;;
+        3) new_value="CALCULATOR" ;;
+        4) new_value="CALENDAR" ;;
+        5) new_value="CALL" ;;
+        6) new_value="CAMERA" ;;
+        7) new_value="CONTACTS" ;;
+        8) new_value="HOME" ;;
+        9) new_value="EXPLORER" ;;
+        10) new_value="MENU" ;;
+        11) new_value="MESSAGE" ;;
+        12) new_value="MEDIA_NEXT" ;;
+        13) new_value="MEDIA_PLAY_PAUSE" ;;
+        14) new_value="MEDIA_PREVIOUS" ;;
+        15) new_value="MUSIC" ;;
+        16) new_value="PAGE_UP" ;;
+        17) new_value="PAGE_DOWN" ;;
+        18) new_value="POWER" ;;
+        19) new_value="QPANEL_ON_OFF" ;;
+        20) new_value="SEARCH" ;;
+        21) new_value="SLEEP" ;;
+        22) new_value="SYSRQ" ;;
+        23) new_value="VOICE_ASSIST" ;;
+        24) new_value="VOLUME_DOWN" ;;
+        25) new_value="VOLUME_MUTE" ;;
+        26) new_value="VOLUME_UP" ;;
+        27) new_value="WAKEUP" ;;
+        *)
+            printf "${INDENTN}${RED}[!] Error: Invalid choice. Please enter${RESET}"
+            printf "${INDENTN}${RED}a number between 1 and 27.${RESET}\n"
+            return
+            ;;
+    esac
+
+    # Update the value
+    temp_file="/data/local/tmp/temp_key_file"
+    grep -v "key $key_code" "$file" > "$temp_file"
+    echo "key $key_code $new_value" >> "$temp_file"
+
+    # Check if we have write permission
+    if ! touch "$file" 2>/dev/null; then
+        printf "${INDENTN}${YELLOW}[!] No write permission. Trying with 'su' command...${RESET}\n"
+        su -c "cp $temp_file $file && chmod 644 $file"
+    else
+        cp "$temp_file" "$file"
+        chmod 644 "$file"
+    fi
+
+    rm "$temp_file"
+
+    printf "${INDENTN}${GREEN}[+] Value for key $buttonc has been updated${RESET}"
+    printf "${INDENTN}${GREEN}to: ${BOLD_WHITE}%s${RESET}" "$new_value"
+    printf "${INDENTN}${YELLOW}[i] Execution Succeed..! ${RESET}\n"
+    printf "${INDENTN}${BLUE}[!] Reboot to apply the changes? (Y/n): ${RESET}"
+    reboot_quest
+}
+
+check_charging() {
+    if [ -f "$CHARGING_PATH" ]; then
+        status=$(cat "$CHARGING_PATH")
+        if [ "$status" -eq 1 ]; then
+            printf "${INDENTN}${GREEN}[i] Charging is currently enabled.${RESET}\n"
+        else
+            printf "${INDENTN}${RED}[i] Charging is currently disabled.${RESET}\n"
+        fi
+    else
+        printf "${INDENTN}${RED}[!] Error: Charging status file not found."
+        exit 1
+    fi
+}
+
+set_charging() {
+    if [ -f "$CHARGING_PATH" ]; then
+        echo "$1" > "$CHARGING_PATH"
+        if [ $? -eq 0 ]; then
+            printf "${INDENTN}${GREEN}[+] Charging has been $2.${RESET}\n"
+        else
+            printf "${INDENTN}${RED}[!] Error: Failed to $2 charging.${RESET}\n"
+        fi
+    else
+        printf "[!] Error: Charging control file not found."
+        exit 1
+    fi
+}
 #Main logic
 case "$1" in
-    batt_b)
-        boost_battery
-        ;;
-    batt_i)
-        battinfo
-        ;;
-    batt_s)
-        battsettings
-        ;;
+    batt)
+        if [ -z "$2" ]; then
+            printf "${INDENT}${RED}Error: Need second argument '$1' '$2'${RESET}"
+            printf "${INDENT}Use '${BOLD}infamick info${RESET}' for usage information."
+            exit 1
+        fi
+        case "$2" in
+            boost)
+            boost_battery
+            ;;
+            info)
+            battinfo
+            ;;
+            opt)
+            battsettings
+            ;;
+            start)
+            set_charging 1 "enabled"
+            ;;
+            status)
+            check_charging
+            ;;
+            stop)
+            set_charging 0 "disabled"
+            ;;
+            *)
+                printf "${INDENT}${RED}Error: Unknown command '$1' '$2'${RESET}"
+                printf "${INDENT}Use '${BOLD}infamick info${RESET}' for usage information."
+                exit 1
+                ;;
+            esac
+        ;;     
     boot)
         boot
+        ;;
+    btmap)
+        button_mapper
         ;;
     cache)
         clear_cache
@@ -991,7 +1215,7 @@ case "$1" in
         case "$2" in
             bx)
                 smg_check || return
-                button_mapper
+                bixby_mapper
                 ;;
             csc)
                 smg_check || return 
