v2.5 RELEASE

diff --git a/infamick b/infamick
--- a/infamick
+++ b/infamick
@@ -410,7 +410,7 @@ services=(
 help_menu() {
     echo
     printf "\n${BOLD}infamick - System Utility Script${RESET}"
-    printf "\n${RED}${BOLD}2.4 (202408192)"
+    printf "\n${RED}${BOLD}2.5 (202408193)"
     echo
     printf "\n${GREEN}Usage:${RESET} infamick ${BOLD}<command> ${BLUE}${BOLD}<2ndcommand>${RESET}"
     echo
@@ -436,9 +436,9 @@ help_menu() {
     printf "\n  ${BOLD}dd${RESET}      - Backup all possible partitions"
     printf "\n            chosing a name"
     echo
-    printf "\n  ${BOLD}dsp_rs${RESET}  - Reset current display size and dpi"
-    printf "\n  ${BOLD}dsp_set${RESET} - Change display size and dpi "
-    printf "\n  ${BOLD}dsp_sw${RESET}  - Show current display size and dpi"
+    printf "\n  ${BOLD}dsp ${BLUE}${BOLD}rs${RESET}  - Reset current display size and dpi"
+    printf "\n  ${BOLD}dsp ${BLUE}${BOLD}set${RESET} - Change display size and dpi "
+    printf "\n  ${BOLD}dsp ${BLUE}${BOLD}sw${RESET}  - Show current display size and dpi"
     echo
     printf "\n  ${BOLD}fix${RESET} ${BLUE}${BOLD}datausage${RESET}  - Fix data usage settings drain"
     printf "\n  ${BOLD}fix${RESET} ${BLUE}${BOLD}gms${RESET}        - Fix GMS drain"
@@ -1190,7 +1190,7 @@ fix_datausage() {
     printf "${INDENTN}${YELLOW}[i]As first I'll redirect u to Access Data"
     printf "${INDENTN}${YELLOW}Usage settings"
     printf "${INDENTN}${YELLOW}U have to:"
-    printf "${INDENTN}${YELLOW}[1] Untick all apps"
+    printf "\n${INDENTN}${YELLOW}[1] Untick all apps"
     printf "${INDENTN}${YELLOW}[2] Tick only those apps: 'Shell',"
     printf "${INDENTN}${YELLOW}'Telephone services','Samsung Device"
     printf "${INDENTN}${YELLOW}Health Manager Service', 'Media Storage','Package"
@@ -1207,7 +1207,7 @@ fix_smgdrain(){
 #Samsung Device Care
     printf "${INDENTN}${YELLOW}[i] As first I'll redirect u to Samsung Device Care"
     printf "${INDENTN}${YELLOW}app info. U have to:"
-    printf "${INDENTN}${YELLOW}[1] Clear app cache"
+    printf "\n${INDENTN}${YELLOW}[1] Clear app cache"
     printf "${INDENTN}${YELLOW}[2] Clear app data"
     printf "${INDENTN}${YELLOW}[3] Uninstall updates" 
     printf "${INDENTN}${YELLOW}[4] Force stop the app"
@@ -1221,7 +1221,7 @@ fix_smgdrain(){
     #Samsung Device Health Service
     printf "${INDENTN}${YELLOW}[i]As second I'll redirect u to Samsung Device"
     printf "${INDENTN}${YELLOW}Health Service app info. U have to:"
-    printf "${INDENTN}${YELLOW}[1] Clear app cache"
+    printf "\n${INDENTN}${YELLOW}[1] Clear app cache"
     printf "${INDENTN}${YELLOW}[2] Clear app data"
     printf "${INDENTN}${YELLOW}[3] Force stop the app"
     printf "${INDENTN}${YELLOW}[i]Press ENTER to redirect...${RESET}"
@@ -1231,7 +1231,7 @@ fix_smgdrain(){
     read -r a 
 #After steps
     printf "${INDENTN}${YELLOW}[i]Now do this steps:"
-    printf "${INDENTN}${YELLOW}[1] Reboot to recovery"
+    printf "\n${INDENTN}${YELLOW}[1] Reboot to recovery"
     printf "${INDENTN}${YELLOW}[2] Clear the cache in the recovery"
     printf "${INDENTN}${YELLOW}[3a] If u are on the stock Recovery do Repair apps"
     printf "${INDENTN}${YELLOW}[3b] If u are on TWRP clear also dalvick cache"
@@ -1241,7 +1241,7 @@ fix_smgdrain(){
     printf "\n${INDENTN}${YELLOW}[i]I'll show u what to do next redirecting"
     printf "${INDENTN}${YELLOW}you to Samsung Device Health Service app info."
     printf "${INDENTN}${YELLOW}U have to:"
-    printf "${INDENTN}${YELLOW}[1] Put in NORMAL sleep all the apps that u want"
+    printf "\n${INDENTN}${YELLOW}[1] Put in NORMAL sleep all the apps that u want"
     printf "${INDENTN}${YELLOW}to receive notifications"
     printf "${INDENTN}${YELLOW}[2] Put to DEEP sleep all the apps that u don't need"
     printf "${INDENTN}${YELLOW}to receive notifications"
@@ -1257,7 +1257,7 @@ fix_gms(){
 #Google PLay Services
     printf "${INDENTN}${YELLOW}[i] As first I'll redirect u to Google Play Services"
     printf "${INDENTN}app info. U have to:"
-    printf "${INDENTN}[1] Clear app cache"
+    printf "\n${INDENTN}[1] Clear app cache"
     printf "${INDENTN}[2] Clear app data"
     printf "${INDENTN}[3] Uninstall updates"
     printf "${INDENTN}[4] Force stop the app"
@@ -1269,7 +1269,7 @@ fix_gms(){
 #Googlee Services Framework
     printf "${INDENTN}${YELLOW}[i]As second I'll redirect u to Google Services"
     printf "${INDENTN}${YELLOW}Framework app info. U have to:"
-    printf "${INDENTN}${YELLOW}[1] Clear app cache"
+    printf "\n${INDENTN}${YELLOW}[1] Clear app cache"
     printf "${INDENTN}${YELLOW}[2] Clear app data"
     printf "${INDENTN}${YELLOW}[3] Force stop the app"
     printf "${INDENTN}${YELLOW}[i]Press ENTER to redirect...${RESET}"
@@ -1280,7 +1280,7 @@ fix_gms(){
 #Android System Webview
     printf "${INDENTN}${YELLOW}[i]As last I'll redirect u to Android System"
     printf "${INDENTN}${YELLOW}Webview app info. U have to:"
-    printf "${INDENTN}${YELLOW}[1] Clear app cache2"
+    printf "\n${INDENTN}${YELLOW}[1] Clear app cache2"
     printf "${INDENTN}${YELLOW}[2] Clear app data"
     printf "${INDENTN}${YELLOW}[3] Uninstall updates"
     printf "${INDENTN}${YELLOW}[4] Force stop the app"
@@ -1290,7 +1290,7 @@ fix_gms(){
     printf "${INDENTN}${GREEN}[i]Press ENTER when u have done${RESET}" 
     read -r a 
     printf "${INDENTN}${YELLOW}[i]Now do this steps:"
-    printf "${INDENTN}${YELLOW}[1] Reboot to recovery"
+    printf "\n${INDENTN}${YELLOW}[1] Reboot to recovery"
     printf "${INDENTN}${YELLOW}[2] Clear the cache in the recovery"
     printf "${INDENTN}${YELLOW}[3a] If u are on the stock Recovery do Repair apps"
     printf "${INDENTN}${YELLOW}[3b] If u are on TWRP clear also dalvick cache"
@@ -1303,7 +1303,7 @@ fix_oneui() {
 #Oneui Launcher
     printf "${INDENTN}${YELLOW}[i] As first I'll redirect u to Oneui"
     printf "${INDENTN}${YELLOW}Launcher app info. U have to:"
-    printf "${INDENTN}${YELLOW}[1] Clear app cache"
+    printf "\n${INDENTN}${YELLOW}[1] Clear app cache"
     printf "${INDENTN}${YELLOW}[2] Clear app data"
     printf "${INDENTN}${YELLOW}[3] Uninstall updates"
     printf "${INDENTN}${YELLOW}[4] Force stop the app"
@@ -1314,7 +1314,7 @@ fix_oneui() {
     read -r a 
 #After steps
     printf "${INDENTN}${YELLOW}Now do this steps:"
-    printf "${INDENTN}${YELLOW}[1] Reboot to recovery"
+    printf "\n${INDENTN}${YELLOW}[1] Reboot to recovery"
     printf "${INDENTN}${YELLOW}[2] Clear the cache in the recovery"
     printf "${INDENTN}${YELLOW}[3a] If u are on the stock Recovery do Repair apps"
     printf "${INDENTN}${YELLOW}[3b] If u are on TWRP clear also dalvick cache"
@@ -1324,6 +1324,7 @@ fix_oneui() {
 }
 
 manage_selinux() {
+printf "${INDENTN}${YELLOW}[i] In stock exynos kernels we cant change SELinux ${INDENTN}    to permissive by default cause in exynos SELinux${INDENTN}    status is forced to enforcing.\n${INDENTN}[i] You should install a kernel which has${INDENTN}    a switchable SELinux\n"
     case "$1" in
         0)
             printf "${INDENTN}${YELLOW}[i] Setting SELinux to Permissive...${RESET}"
@@ -1393,14 +1394,27 @@ case "$1" in
     dd)
         dd_backup
         ;;
-    dsp_rs)
-        display_reset
-        ;;
-    dps_set)
-        display_set
-        ;;
-    dsp_sw)
-        display_see
+    dsp)
+        if [ -z "$2" ]; then
+            printf "${INDENT}${RED}Error: Need second argument '$1' '$2'${RESET}"
+            printf "${INDENTN}Use '${BOLD}infamick info${RESET}' for usage information.\n"
+            exit 1
+        fi
+        case "$2" in
+            rs)
+            display_reset
+            ;;
+            set)
+            display_reset;;
+            sw)
+            display_see
+            ;;
+            *)
+                printf "${INDENT}${RED}Error: Unknown command '$1' '$2'${RESET}"
+                printf "${INDENTN}Use '${BOLD}infamick info${RESET}' for usage information.\n"
+                exit 1
+                ;;
+            esac
         ;;
     fix)
             if [ -z "$2" ]; then
