v2.2 RELEASE

diff --git a/infamick b/infamick
--- a/infamick
+++ b/infamick
@@ -410,7 +410,7 @@ services=(
 help_menu() {
     echo
     printf "\n${BOLD}infamick - System Utility Script${RESET}"
-    printf "\n${RED}${BOLD}2.1 (202408079)"
+    printf "\n${RED}${BOLD}2.2 (202408189)"
     echo
     printf "\n${GREEN}Usage:${RESET} infamick ${BOLD}<command> ${BLUE}${BOLD}<2ndcommand>${RESET}"
     echo
@@ -440,6 +440,12 @@ help_menu() {
     printf "\n  ${BOLD}dsp_set${RESET} - Change display size and dpi "
     printf "\n  ${BOLD}dsp_sw${RESET}  - Show current display size and dpi"
     echo
+    printf "\n  ${BOLD}fix${RESET} ${BLUE}${BOLD}datausage${RESET}  - Fix data usage settings drain"
+    printf "\n  ${BOLD}fix${RESET} ${BLUE}${BOLD}gms${RESET}        - Fix GMS drain"
+    printf "\n  ${BOLD}fix${RESET} ${BLUE}${BOLD}oneui${RESET}      - Fix Oneui drain"
+    printf "\n  ${BOLD}fix${RESET} ${BLUE}${BOLD}smgcare${RESET}    - Fix general apps drain in"
+    printf "\n                   Samsung Device Care"
+    echo
     printf "\n  ${BOLD}gmsd${RESET}    - Disables GMS services"
     printf "\n  ${BOLD}gmse${RESET}    - Enables GMS services"
     echo
@@ -468,7 +474,8 @@ help_menu() {
     echo
     printf "\n  ${BOLD}smg${RESET} ${BLUE}${BOLD}ntw_l${RESET} - Open Network Bands settings"
     echo
-    printf "\n  ${BOLD}sot${RESET}     - Calculate how SOT is possible with 100% battery"
+    printf "\n  ${BOLD}sot${RESET}     - Calculate how SOT is possible with 100"
+    printf "\n            battery"
     printf "\n            Requires:"
     printf "\n              - Current SOT hours and minutes values"
     printf "\n              - Discharged percentage value"
@@ -1172,12 +1179,151 @@ set_charging() {
         exit 1
     fi
 }
+fix_datausage() {
+    #Access data usage
+    printf "${INDENTN}${YELLOW}[i]As first I'll redirect u to Access Data"
+    printf "${INDENTN}${YELLOW}Usage settings"
+    printf "${INDENTN}${YELLOW}U have to:"
+    printf "${INDENTN}${YELLOW}[1] Untick all apps"
+    printf "${INDENTN}${YELLOW}[2] Tick only those apps: 'Shell',"
+    printf "${INDENTN}${YELLOW}'Telephone services','Samsung Device"
+    printf "${INDENTN}${YELLOW}Health Manager Service', 'Media Storage','Package"
+    printf "${INDENTN}${YELLOW}installation','User Settings'"
+    printf "${INDENTN}${YELLOW}'Permission checker app'."
+    printf "${INDENTN}${YELLOW}[i]Press ENTER to redirect...${RESET}"
+    read -r a
+    am start -n com.android.settings/.Settings\$UsageAccessSettingsActivity -a android.intent.action.VIEW -d package:com.samsung.android.app.routines > /dev/null 2>&1
+    printf "${INDENTN}${YELLOW}Enjoy :)${RESET}\n"
+    read -r a 
+}
+
+fix_smgdrain(){
+#Samsung Device Care
+    printf "${INDENTN}${YELLOW}[i] As first I'll redirect u to Samsung Device Care"
+    printf "${INDENTN}${YELLOW}app info. U have to:"
+    printf "${INDENTN}${YELLOW}[1] Clear app cache"
+    printf "${INDENTN}${YELLOW}[2] Clear app data"
+    printf "${INDENTN}${YELLOW}[3] Uninstall updates" 
+    printf "${INDENTN}${YELLOW}[4] Force stop the app"
+    printf "${INDENTN}${YELLOW}[i]Press ENTER to redirect...${RESET}"
+    read -r a
+    if [ -z $(am start -n com.android.settings/.applications.InstalledAppDetailsTop -a android.intent.action.VIEW -d package:com.samsung.android.lool > /dev/null 2>&1) ]; then
+         am start -n com.android.settings/.applications.InstalledAppDetailsTop -a android.intent.action.VIEW -d package:com.samsung.android.sm_cn > /dev/null 2>&1
+    fi
+    printf "${INDENTN}${GREEN}[i]Press ENTER when u have done${RESET}" 
+    read -r a 
+    #Samsung Device Health Service
+    printf "${INDENTN}${YELLOW}[i]As second I'll redirect u to Samsung Device"
+    printf "${INDENTN}${YELLOW}Health Service app info. U have to:"
+    printf "${INDENTN}${YELLOW}[1] Clear app cache"
+    printf "${INDENTN}${YELLOW}[2] Clear app data"
+    printf "${INDENTN}${YELLOW}[3] Force stop the app"
+    printf "${INDENTN}${YELLOW}[i]Press ENTER to redirect...${RESET}"
+    read -r a
+    am start -n com.android.settings/.applications.InstalledAppDetailsTop -a android.intent.action.VIEW -d package:com.sec.android.sdhms > /dev/null 2>&1
+    printf "${INDENTN}${GREEN}[i]Press ENTER when u have done${RESET}" 
+    read -r a 
+#After steps
+    printf "${INDENTN}${YELLOW}[i]Now do this steps:"
+    printf "${INDENTN}${YELLOW}[1] Reboot to recovery"
+    printf "${INDENTN}${YELLOW}[2] Clear the cache in the recovery"
+    printf "${INDENTN}${YELLOW}[3a] If u are on the stock Recovery do Repair apps"
+    printf "${INDENTN}${YELLOW}[3b] If u are on TWRP clear also dalvick cache"
+    printf "${INDENTN}${YELLOW}[3a] and reboot system"
+    printf "${INDENTN}${YELLOW}[4] Check for updates for Samsung Device Care."
+    #Samsung Device care settings
+    printf "\n${INDENTN}${YELLOW}[i]I'll show u what to do next redirecting"
+    printf "${INDENTN}${YELLOW}you to Samsung Device Health Service app info."
+    printf "${INDENTN}${YELLOW} U have to:"
+    printf "${INDENTN}${YELLOW}[1] Put in NORMAL sleep all the apps that u want"
+    printf "${INDENTN}${YELLOW} to receive notifications"
+    printf "${INDENTN}${YELLOW}[2] Put to DEEP sleep all the apps that u don't need"
+    printf "${INDENTN}${YELLOW} to receive notifications"
+    printf "${INDENTN}${YELLOW}[3] Disable Adaptive Battery"
+    printf "\n${INDENTN}${YELLOW}Enjoy :)${RESET}\n"
+    read -r a
+    if [ -z $( am start -n com.samsung.android.lool/com.samsung.android.sm.battery.ui.BatteryActivity > /dev/null 2>&1) ]; then
+         am start -n com.samsung.android.sm_cn/com.samsung.android.sm.battery.ui.BatteryActivity > /dev/null 2>&1
+    fi
+}
+
+fix_gms(){
+#Google PLay Services
+    printf "${INDENTN}${YELLOW}[i] As first I'll redirect u to Google Play Services"
+    printf "${INDENTN}app info. U have to:"
+    printf "${INDENTN}[1] Clear app cache"
+    printf "${INDENTN}[2] Clear app data"
+    printf "${INDENTN}[3] Uninstall updates"
+    printf "${INDENTN}[4] Force stop the app"
+    printf "${INDENTN}${YELLOW}[i]Press ENTER to redirect...${RESET}"
+    read -r a
+    am start -n com.android.settings/.applications.InstalledAppDetailsTop -a android.intent.action.VIEW -d package:com.google.android.gms > /dev/null 2>&1
+    printf "${INDENTN}${GREEN}[i]Press ENTER when u have done${RESET}" 
+    read -r a 
+#Googlee Services Framework
+    printf "${INDENTN}${YELLOW}[i]As second I'll redirect u to Google Services"
+    printf "${INDENTN}${YELLOW}Framework app info. U have to:"
+    printf "${INDENTN}${YELLOW}[1] Clear app cache"
+    printf "${INDENTN}${YELLOW}[2] Clear app data"
+    printf "${INDENTN}${YELLOW}[3] Force stop the app"
+    printf "${INDENTN}${YELLOW}[i]Press ENTER to redirect...${RESET}"
+    read -r a
+    am start -n com.android.settings/.applications.InstalledAppDetailsTop -a android.intent.action.VIEW -d package:com.google.android.gsf > /dev/null 2>&1
+    printf "${INDENTN}${GREEN}[i]Press ENTER when u have done${RESET}" 
+    read -r a 
+#Android System Webview
+    printf "${INDENTN}${YELLOW}[i]As last I'll redirect u to Android System"
+    printf "${INDENTN}${YELLOW}Webview app info. U have to:"
+    printf "${INDENTN}${YELLOW}[1] Clear app cache2"
+    printf "${INDENTN}${YELLOW}[2] Clear app data"
+    printf "${INDENTN}${YELLOW}[3] Uninstall updates"
+    printf "${INDENTN}${YELLOW}[4] Force stop the app"
+    printf "${INDENTN}${YELLOW}[i]Press ENTER to redirect...${RESET}"
+    read -r a
+    am start -n com.android.settings/.applications.InstalledAppDetailsTop -a android.intent.action.VIEW -d package:com.google.android.webview > /dev/null 2>&1
+    printf "${INDENTN}${GREEN}[i]Press ENTER when u have done${RESET}" 
+    read -r a 
+    printf "${INDENTN}${YELLOW}[i]Now do this steps:"
+    printf "${INDENTN}${YELLOW}[1] Reboot to recovery"
+    printf "${INDENTN}${YELLOW}[2] Clear the cache in the recovery"
+    printf "${INDENTN}${YELLOW}[3a] If u are on the stock Recovery do Repair apps"
+    printf "${INDENTN}${YELLOW}[3b] If u are on TWRP clear also dalvick cache"
+    printf "${INDENTN}${YELLOW}and reboot system"
+    printf "${INDENTN}${YELLOW}[4] Check for updates for Google Play Services,"
+    printf "${INDENTN}${YELLOW}Google Play Store and Android System webview"
+    printf "\n${INDENTN}${YELLOW}Enjoy :)${RESET}\n"
+   }
+fix_oneui() {
+#Oneui Launcher
+    printf "${INDENTN}${YELLOW}[i] As first I'll redirect u to Oneui"
+    printf "${INDENTN}${YELLOW}Launcher app info. U have to:"
+    printf "${INDENTN}${YELLOW}[1] Clear app cache"
+    printf "${INDENTN}${YELLOW}[2] Clear app data"
+    printf "${INDENTN}${YELLOW}[3] Uninstall updates"
+    printf "${INDENTN}${YELLOW}[4] Force stop the app"
+    printf "${INDENTN}${YELLOW}[i]Press ENTER to redirect...${RESET}"
+    read -r a 
+    am start -n com.android.settings/.applications.InstalledAppDetailsTop -a android.intent.action.VIEW -d package:com.sec.android.app.launcher > /dev/null 2>&1
+    printf "${INDENTN}${GREEN}[i]Press ENTER when u have done${RESET}" 
+    read -r a 
+#After steps
+    printf "${INDENTN}${YELLOW}Now do this steps:"
+    printf "${INDENTN}${YELLOW}[1] Reboot to recovery"
+    printf "${INDENTN}${YELLOW}[2] Clear the cache in the recovery"
+    printf "${INDENTN}${YELLOW}[3a] If u are on the stock Recovery do Repair apps"
+    printf "${INDENTN}${YELLOW}[3b] If u are on TWRP clear also dalvick cache"
+    printf "${INDENTN}${YELLOW}and reboot system"
+    printf "${INDENTN}${YELLOW}[4] Check for updates for OneUI in Galaxy store"
+    printf "\n${INDENTN}${YELLOW}Enjoy :)${RESET}\n"
+}
+
+
 #Main logic
 case "$1" in
     batt)
         if [ -z "$2" ]; then
             printf "${INDENT}${RED}Error: Need second argument '$1' '$2'${RESET}"
-            printf "${INDENT}Use '${BOLD}infamick info${RESET}' for usage information."
+            printf "${INDENTN}Use '${BOLD}infamick info${RESET}' for usage information.\n"
             exit 1
         fi
         case "$2" in
@@ -1201,7 +1347,7 @@ case "$1" in
             ;;
             *)
                 printf "${INDENT}${RED}Error: Unknown command '$1' '$2'${RESET}"
-                printf "${INDENT}Use '${BOLD}infamick info${RESET}' for usage information."
+                printf "${INDENTN}Use '${BOLD}infamick info${RESET}' for usage information.\n"
                 exit 1
                 ;;
             esac
@@ -1227,6 +1373,35 @@ case "$1" in
     dsp_sw)
         display_see
         ;;
+    fix)
+            if [ -z "$2" ]; then
+            printf "${INDENT}${RED}Error: Need second argument '$1' '$2'${RESET}"
+            printf "${INDENTN}Use '${BOLD}infamick info${RESET}' for usage information.\n"
+            exit 1
+        fi
+        case "$2" in
+            datausage)
+                smg_check || return
+                fix_datausage
+                ;;
+            gms)
+                fix_gms
+                ;;
+            oneui)
+                smg_check || return
+                fix_oneui
+                ;;
+            smgcare)
+                smg_check || return
+                fix_smgdrain
+                ;;        
+            *)
+                printf "${INDENT}${RED}Error: Unknown command '$1' '$2'${RESET}"
+                printf "${INDENTN}Use '${BOLD}infamick info${RESET}' for usage information.\n"
+                exit 1
+                ;;
+            esac
+        ;;
     gmsd)
         gms_disable
         ;;
@@ -1239,7 +1414,7 @@ case "$1" in
     smg)
         if [ -z "$2" ]; then
             printf "${INDENT}${RED}Error: Need second argument '$1' '$2'${RESET}"
-            printf "${INDENT}Use '${BOLD}infamick info${RESET}' for usage information."
+            printf "${INDENTN}Use '${BOLD}infamick info${RESET}' for usage information.\n"
             exit 1
         fi
         case "$2" in
@@ -1277,7 +1452,7 @@ case "$1" in
                 ;;
             *)
                 printf "${INDENT}${RED}Error: Unknown command '$1' '$2'${RESET}"
-                printf "${INDENT}Use '${BOLD}infamick info${RESET}' for usage information."
+                printf "${INDENTN}Use '${BOLD}infamick info${RESET}' for usage information.\n"
                 exit 1
                 ;;
             esac
@@ -1293,7 +1468,7 @@ case "$1" in
         ;;
     *)
         printf "${INDENT}${RED}Error: Unknown command '$1'${RESET}"
-        printf "${INDENT}Use '${BOLD}infamick info${RESET}' for usage information."
+        printf "${INDENTN}Use '${BOLD}infamick info${RESET}' for usage information.\n"
         exit 1
         ;;
 esac
