v2.4 RELEASE

diff --git a/infamick b/infamick
--- a/infamick
+++ b/infamick
@@ -410,7 +410,7 @@ services=(
 help_menu() {
     echo
     printf "\n${BOLD}infamick - System Utility Script${RESET}"
-    printf "\n${RED}${BOLD}2.3 (202408191)"
+    printf "\n${RED}${BOLD}2.4 (202408192)"
     echo
     printf "\n${GREEN}Usage:${RESET} infamick ${BOLD}<command> ${BLUE}${BOLD}<2ndcommand>${RESET}"
     echo
@@ -454,6 +454,10 @@ help_menu() {
     printf "\n  ${BOLD}-h${RESET}      - Alias for info"
     echo
     printf "\n  ${BOLD}perf${RESET}    - Boost all apps"
+    echo
+    printf "\n  ${BOLD}selinux${RESET} ${BLUE}${BOLD}0${RESET}    - Set SELinux state to Permissive"
+    printf "\n  ${BOLD}selinux${RESET} ${BLUE}${BOLD}1${RESET}    - Set SELinux state to Enforcing"
+    printf "\n  ${BOLD}selinux${RESET} ${BOLD}${BLUE}get${RESET}  - Show current SELinux state" 
     echo
     printf "\n  ${BOLD}smg${RESET} ${BLUE}${BOLD}<2ndcommand>${RESET}  ${YELLOW}${BOLD}Samsung Tweaks${RESET}" 
     echo
@@ -1319,6 +1323,29 @@ fix_oneui() {
     printf "\n${INDENTN}${YELLOW}Enjoy :)${RESET}\n"
 }
 
+manage_selinux() {
+    case "$1" in
+        0)
+            printf "${INDENTN}${YELLOW}[i] Setting SELinux to Permissive...${RESET}"
+            setenforce 0
+            printf "${INDENTN}${GREEN}[+] SELinux has been set to Permissive.${RESET}\n"
+            ;;
+        1)
+            printf "${INDENTN}${YELLOW}[i] Setting SELinux to Enforcing...${RESET}"
+            setenforce 1
+            printf "${INDENTN}${GREEN}[+] SELinux has been set to Enforcing.${RESET}\n"
+            ;;
+        get)
+            printf "${INDENTN}${YELLOW}[*] Current SELinux status: ${BOLD_WHITE}%s${RESET}" "$(getenforce)"
+            ;;
+        *)
+            printf "${INDENTN}${RED}[!] Error: Invalid SELinux option. Please use 0, 1, or 'get'.${RESET}\n"
+            exit 1
+            ;;
+    esac
+
+    printf "${INDENTN}${YELLOW}[i] Operation completed successfully.${RESET}\n"
+}
 
 #Main logic
 case "$1" in
@@ -1412,6 +1439,9 @@ case "$1" in
         ;;
     perf)
         boost_app
+        ;;
+    selinux)
+        manage_selinux "$2"
         ;;
     smg)
         if [ -z "$2" ]; then
